# Grafana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana-stack
  labels:
    app: grafana
    name: grafana
    tier: grafana
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: secrets-store-sa
      automountServiceAccountToken: true
      restartPolicy: Always
      containers:
      - name: grafana
        image: grafana/grafana:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "250m"
          requests:
            memory: "256Mi"
            cpu: "125m"
        ports:
        - containerPort: 3000
        command: ["/bin/sh", "-c"]
        args:
          - |
            TENANT_ID=$(cat /mnt/secrets-store/azure-tenant-id)
            export GF_AUTH_AZUREAD_AUTH_URL="https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/authorize"
            export GF_AUTH_AZUREAD_TOKEN_URL="https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token"
            exec /run.sh
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD__FILE
          value: /mnt/secrets-store/admin-password
        - name: GF_AUTH_AZUREAD_ENABLED
          value: "true"
        - name: GF_AUTH_AZUREAD_NAME
          value: "SSO"
        - name: GF_AUTH_AZUREAD_CLIENT_ID__FILE
          value: /mnt/secrets-store/azure-client-id
        - name: GF_AUTH_AZUREAD_CLIENT_SECRET__FILE
          value: /mnt/secrets-store/azure-client-secret
        - name: GF_AUTH_AZUREAD_TENANT_ID__FILE
          value: /mnt/secrets-store/azure-tenant-id
        - name: GF_SERVER_ROOT_URL
          value: https://ALB_PLACE_HOLDER/grafana/
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: grafana-secrets